openapi: "3.0.0"

info:
  title: API de Ecommerce #ca sera utiliser pour les endPoint @RequestMapping("${openapi.aPIDeTest.base-path:/service/api}")
  version: "1.0"
  description: Test de openAPI

servers:
  - url: http://localhost:8080/ecommerce/api

tags:
  - name: Client
    description: Client specific data.
  - name: Article
    description: Article specific data.
  - name: Commande
    description: Commande specific data.

paths:

  ##############
  ## API Client ##
  ##############

  /clients:
    $ref: '../components/api/client.yml#/paths/~1clients'

  /clients/{idClient}:
    $ref: '../components/api/client.yml#/paths/~1clients-reference'

  ##############
  ## API Commande ##
  ##############

  /commandes:
    $ref: '../components/api/commande.yml#/paths/~1commandes'

  /commandesByClient:
    $ref: '../components/api/commande.yml#/paths/~1commandesByClient'

  /commandesByStatut:
    $ref: '../components/api/commande.yml#/paths/~1commandesByStatut'

  /commandes/{idCommande}:
    $ref: '../components/api/commande.yml#/paths/~1commandes-reference'

  ##############
  ## API Produits ##
  ##############

  /articles:
    $ref: '../components/api/article.yml#/paths/~1articles'

  /articles/{idProduct}:
    $ref: '../components/api/article.yml#/paths/~1articles-reference'