openapi: "3.0.0"

info:
  title: API de Test #ca sera utiliser pour les endPoint @RequestMapping("${openapi.aPIDeTest.base-path:/service/api}")
  version: "1.0"
  description: Test de openAPI

servers:
  - url: http://localhost:8080/service/api

tags:
  - name: Client
    description: Client specific data.

paths:

  ##############
  ## API Client ##
  ##############

  /clients:
    $ref: '../components/api/client.yml#/paths/%2Fclients'

  /clients/{idClient}:
    $ref: '../components/api/client.yml#/paths/%2Fclients-reference'

