/**
 * API de Ecommerce
 * Test de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandeDTO } from './commandeDTO';


export interface CommandeResultListByClientDTO { 
    /**
     * Fonctionnel id of the customer
     */
    idClient?: number;
    /**
     * The List of the CommandeResultDTO by client
     */
    commandeList?: Array<CommandeDTO>;
}

