/**
 * API de Ecommerce
 * Test de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandeResultDTO } from './commandeResultDTO';


export interface CommandeResultListDTO { 
    /**
     * The List of the CommandeResultDTO
     */
    commandeList?: Array<CommandeResultDTO>;
}

