/**
 * API de Ecommerce
 * Test de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientDTO } from './clientDTO';
import { ArticleDTO } from './articleDTO';


export interface CommandeResultDTO { 
    /**
     * Fonctionnel id of the customer
     */
    idCommande?: number;
    client?: ClientDTO;
    /**
     * The List of produit and their commande
     */
    produits?: Array<ArticleDTO>;
}

