openapi: "3.0.0"

info:
  title: API Article
  version: "1.0"
  description: Ecommerce API

servers:
  - url: http://localhost:8080/ecommerce/api

tags:
  - name: Article
    description: Article specific data.

paths:
  /articles:
    get:
      tags:
        - Article
      summary: Get All Actifs Articles
      operationId: getAllArticles
      parameters:
        - name: currentPage
          in: query
          required: true
          schema:
            type: integer
            format: int32
        - name: sizePage
          in: query
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/article/ArticleResultListDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST

  /articles-reference:
    get:
      tags:
        - Product
      summary: Retrieve an Product
      operationId: getProduct
      parameters:
        - name: idProduct
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/article/ArticleDTO.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
