/**
 * API de Ecommerce
 * Test de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandeDTO } from './commandeDTO';


export interface ArticleDTO { 
    /**
     * ID of the product
     */
    idProduct?: number;
    /**
     * description of the product
     */
    description?: string;
    /**
     * quantity of the product
     */
    quantity?: number;
    /**
     * The List of produit and their commandes
     */
    commandes?: Array<CommandeDTO>;
}

