/**
 * API de Ecommerce
 * Test de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientResultDTO } from './clientResultDTO';


export interface ClientResultListDTO { 
    /**
     * The List of the ClientResultDTO
     */
    clientList?: Array<ClientResultDTO>;
}

