/**
 * API de Ecommerce
 * Test de openAPI
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StatusCommande = 'NEW' | 'VALIDATED' | 'IN_PROGRESS' | 'TO_COMPLETE' | 'CLOSED';

export const StatusCommande = {
    NEW: 'NEW' as StatusCommande,
    VALIDATED: 'VALIDATED' as StatusCommande,
    INPROGRESS: 'IN_PROGRESS' as StatusCommande,
    TOCOMPLETE: 'TO_COMPLETE' as StatusCommande,
    CLOSED: 'CLOSED' as StatusCommande
};

